### ISSUE TITLE
Viewing past data via the calendar no longer working

### ISSUE THREAD

**Issue by PaulRobson** [rob-miller/rTracker#6]
Before the update it used to be possible to view and edit past data by selecting a blue date on the calendar, but this doesn’t work anymore. When you pick a date the app stays on creating a new entry.

**Comment by rob-miller** [comment]
Interesting.  Thanks, I had not noticed that.
There's still swipe left/right to move between dates as a temporary
workaround, but I will get this fixed.
r.

**Comment by rob-miller** [comment]
Closed with release 3.2.1 on App Store.
